### PR TITLE
Create static.yml

### PR DESCRIPTION
**Pull request by N-J-Martin**
trying to set up a workflow to host conjure-blocks

### CODE REVIEW

**Comment by N-J-Martin** [comment]
Does tihs create a github page link? or do I need to add that in. Can't see the settings button on this repo to make a site.

**Comment by ozgurakgun** [comment]
did you take a look at these: https://github.com/conjure-cp/task-allocation-demo/tree/main/.github/workflows

having a test one that merely builds, and a deploy one that builds and deploys is a good idea I think. this was we can run the test one for PRs for sanity checking.

**Comment by ozgurakgun** [comment]
also: instead of storing dist in the repo, we want to build it like so: https://github.com/conjure-cp/task-allocation-demo/blob/1337ef5a158cf2b1e057a05663fa977749d6bbc9/.github/workflows/deploy.yml#L23-L28

maybe one of @niklasdewally, @lixitrixi, @gskorokhod can lend a hand here

**Comment by niklasdewally** [comment]
This LGTM, all it needs is another step that does the build as Oz said.

I don't think we want one version of the site per PR (as we do with conjure oxide coverage) - this would make the pages repo very big for not much benefit! You could probably just do 

```
npm ci
npm build
```

and see if there are any errors. (Javascript debug modes are *way* more lenient than production modes)

**Comment by ozgurakgun** [comment]
we can probably copy the 2 files from the first link I shared (almost) verbatim.

**Comment by N-J-Martin** [comment]
actions are more complicated then I thought. Would anyone mind sitting down with me next week and explain what each section does and what you intend here? thank you.

**Comment by niklasdewally** [comment]
Merging this to test it

**Pull request merged**
